name: podcast
description: "The Flutterest Podcast App Ever"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  build_runner: ^2.4.12
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.2.1
  collection: ^1.18.0
  dio: ^5.6.0
  file: ^7.0.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_ui_firestore: ^1.6.4
#  firebase_ui_firestore:
#    git:
#      url: https://github.com/firebase/FirebaseUI-Flutter.git
#      path: packages/firebase_ui_firestore
#      ref: 9082661a7a41dcdac7a30250baf65da67c9ca2d5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_widget_from_html_core: ^0.15.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.2.3
  google_sign_in: ^6.2.1
  hashlib: ^1.19.2
  hooks_riverpod: ^3.0.0-dev.3
  integral_isolates: ^0.5.1
  intl: ^0.19.0
  json_serializable: ^6.8.0
  just_audio: ^0.9.39
  path_provider: ^2.1.4
  rive: ^0.13.12
  riverpod_annotation: ^3.0.0-dev.3
  rxdart: ^0.28.0
  timeago_flutter: ^3.7.0
  url_launcher: ^6.3.0
  vector_graphics: ^1.1.11+1
  xml: ^6.5.0

dev_dependencies:
  custom_lint: any
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  vector_graphics_compiler: ^1.1.11+1

dependency_overrides:
  rxdart: ^0.28.0
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - path: assets/vectors/
      transformers:
        - package: vector_graphics_compiler
