name: podcast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_service: ^0.18.13
  audio_session: ^0.1.19
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  collection: ^1.18.0
  dio: ^5.4.3+1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_widget_from_html_core: ^0.14.12
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^14.1.0
  google_sign_in: ^6.2.1
  hashlib: ^1.15.0
  hooks_riverpod: ^3.0.0-dev.3
  integral_isolates: ^0.5.1
  intl: ^0.19.0
  json_serializable: ^6.8.0
  just_audio: ^0.9.37
  path_provider: ^2.1.3
  riverpod_annotation: ^3.0.0-dev.3
  rxdart: ^0.27.7
  timeago_flutter: ^3.6.0
  xml: ^6.5.0

dev_dependencies:
  custom_lint: any
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true

dependency_overrides:
  intl: ^0.19.0
