name: podcast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_service: ^0.18.13
  audio_session: ^0.1.19
  build_runner: ^2.4.9
  cloud_firestore: ^4.17.2
  collection: ^1.18.0
  dio: ^5.4.3+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  google_sign_in: ^6.2.1
  hashlib: ^1.14.0
  hooks_riverpod: ^2.5.1
  integral_isolates: ^0.5.1
  intl: ^0.18.1
  json_serializable: ^6.8.0
  just_audio: ^0.9.37
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  xml: ^6.5.0

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

dependency_overrides:
  intl: ^0.19.0
