name: lohnn_podcast_workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  html: ^0.15.5

dev_dependencies:
  melos: ^7.0.0-dev.7

workspace:
  - apps/podcast

melos:
  command:
    version:
#      branch: main
    bootstrap:
      environment:
        sdk: '>=3.7.0 <4.0.0'
        flutter: 3.29.1
            
  scripts:
    generate:
      exec: dart run build_runner build -d
      description: Run code generation.
