name: lohnn_podcast_workspace
workspace:
  - apps/podcast
  - packages/podcast_core
  - packages/podcast_common

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  glob: ^2.1.3
  html: ^0.15.5
  pubspec_parse: ^1.5.0

dev_dependencies:
  melos: ^7.0.0-dev.8

melos:
  command:
    version:
      # Only allow versioning to happen on main branch.
      branch: main
    bootstrap:
      environment:
        sdk: '>=3.8.0 <4.0.0'
        flutter: 3.32.0
  
  scripts:
    generate:
      exec: dart run build_runner build -d
      description: Run code generation.
