name: podcast
description: "The Flutterest Podcast App Ever"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  audio_service: ^0.18.16
  audio_session: ^0.1.23
  brick_offline_first: ^3.3.0
  brick_offline_first_with_supabase: ^1.1.2
  brick_sqlite: ^3.1.1+1
  brick_supabase: ^1.1.3
  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  dart_mappable: ^4.3.0
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_widget_from_html_core: ^0.15.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  hashlib: ^1.21.1
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  just_audio: ^0.9.42
  path_provider: ^2.1.5
  rive:   ^0.13.20
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.8.2
  timeago_flutter: ^3.7.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vector_graphics: ^1.1.15
  xml: ^6.5.0

dev_dependencies:
  brick_offline_first_build: ^3.2.1
  brick_offline_first_with_supabase_build: ^1.0.0
  custom_lint: ^0.7.0
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  vector_graphics_compiler: ^1.1.16

dependency_overrides:
  rxdart: ^0.28.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - path: assets/vectors/
      transformers:
        - package: vector_graphics_compiler
