// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:podcast/repository/adapters/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EpisodeImplAdapter());
    registerAdapter(EpisodeUserStatusAdapter());
    registerAdapter(PlayQueueItemAdapter());
    registerAdapter(PodcastSearchAdapter());
    registerAdapter(UserEpisodeStatusImplAdapter());
  }
}
