name: podcast_common
description: Common (pure Dart) functionality shared between the podcast app and the eventual backend
publish_to: 'none'
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.24.0
