name: podcast
description: "The Flutterest Podcast App Ever"
publish_to: 'none'
version: 0.1.6

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: 3.29.3
resolution: workspace

dependencies:
  brick_offline_first: ^4.0.0
  brick_offline_first_with_supabase: ^2.0.0
  brick_sqlite: ^4.0.1
  brick_supabase: ^2.0.0
  dart_mappable: ^4.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4
  hooks_riverpod: ^2.6.1
  logging: ^1.3.0
  podcast_core: any
  rive: ^0.13.20
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  sqflite_common: ^2.5.5
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.8.4
  xml: ^6.5.0

dev_dependencies:
  brick_offline_first_build: ^4.0.0
  brick_offline_first_with_supabase_build: ^2.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.5.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
