name: podcast
description: "The Flutterest Podcast App Ever"
publish_to: 'none'
version: 0.1.6

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: 3.29.3
resolution: workspace

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  dart_mappable: ^4.5.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  hooks_riverpod: ^3.0.0-dev.15
  logging: ^1.3.0
  podcast_common: any
  podcast_core: any
  rive: ^0.13.20
  riverpod_annotation: ^3.0.0-dev.15
  rxdart: ^0.28.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.5.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2
  lint: ^2.8.0
  riverpod_generator: ^3.0.0-dev.15
  riverpod_lint: ^3.0.0-dev.15

flutter:
  uses-material-design: true
