name: podcast_core
description: "The core library for the Flutterest Podcast App"
publish_to: 'none'
version: 0.1.6

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: 3.29.3
resolution: workspace

dependencies:
  async: ^2.12.0
  audio_service: ^0.18.17
  audio_session: ^0.1.25
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  custom_adaptive_scaffold: ^2.0.1
  dart_mappable: ^4.5.0
  dio: ^5.8.0+1
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_widget_from_html_core: ^0.16.0
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  just_audio: ^0.9.46
  logging: ^1.3.0
  path_provider: ^2.1.5
  rive: ^0.13.20
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  timeago_flutter: ^3.7.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.5.0
  lint: ^2.8.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
