# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to beta testers

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create project_setup_config.json
        run: echo '${{ secrets.PROJECT_SETUP_CONFIG }}' > project_setup_config.json
      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_ANDROID }}' > android/app/google-services.json
      - name: Create firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS_DART }}" > lib/default_firebase_config.dart
    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Setup project config
        run: dart bin/setup_project.dart -f project_setup_config.json

      - name: Pub get
        run: flutter pub get

      - name: Build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android app
        run: flutter build apk --release

      - name: Upload to App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: default-test-group
          releaseNotes: Ny uppdatering av appen!
          file: build/app/outputs/flutter-apk/app-release.apk

      # TODO: Release notes?
      # TODO: Bump version?
