# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to beta testers

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create project_setup_config.json
        env:
          PROJECT_SETUP_CONFIG: ${{ secrets.PROJECT_SETUP_CONFIG }}
        run: echo $PROJECT_SETUP_CONFIG > project_setup_config.json
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}
        run: echo $GOOGLE_SERVICES_ANDROID > apps/podcast/android/app/google-services.json
      - name: Create firebase_options.dart
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: echo $FIREBASE_OPTIONS_DART > apps/podcast/lib/default_firebase_config.dart
      - name: Create keystore
        env:
          KEYSTORE: ${{ secrets.PODCAST_RELEASE_KEYSTORE }}
        run: echo $KEYSTORE > base64 --decode podcast_release.keystore
    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: apps/podcast/pubspec.yaml

      - name: Setup melos
        run: flutter pub global activate melos
      - name: Bootstrap melos
        run: melos bootstrap
        # TODO: Bump version

      - name: Setup project config
        run: dart bin/setup_project.dart -f project_setup_config.json

      - name: Pub get
        run: flutter pub get

      - name: Build runner
        run: melos generate

      - name: Build Android app
        env: 
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: melos exec -- flutter build apk --release --build-number=${{github.run_number}}

      - name: Upload to App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        if: github.ref == 'refs/heads/main'
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: default-test-group
          releaseNotes: Ny uppdatering av appen!
          # TODO: Release notes from melos
          file: apps/podcast/build/app/outputs/flutter-apk/app-release.apk
